services:
  app:
    container_name: fsap_app
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8080
      --reload
      "
    volumes:
      - .:/home/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres_d
    environment:
      POSTGRES_DB: lorry
      POSTGRES_USER: root
      POSTGRES_PASSWORD: imbroot
    ports:
      - "5438:5432"  # Expose port 5432 for PostgreSQL
    networks:
      - app-network

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6380:6379"  # Expose Redis port on the host
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  fastapi_postgres_data: {}

